apiVersion: v1
kind: Endpoints
metadata:
  name: kubernetes-vip
  namespace: default
  labels:
    endpointslice.kubernetes.io/managed-by: endpoint-copier-operator
subsets:
- addresses:
  - ip: 1.1.1.1
  ports:
  - port: 6443
    protocol: TCP